blank_issues_enabled: false
contact_links:
  - name: Question / Help
    url: https://github.com/autonomousvision/sdfstudio/discussions
    about: Ask questions and get help in Discussions
  - name: Documentation
    url: https://docs.nerf.studio
    about: Check the documentation for usage and tutorials
